export const ANSWERS_SHOWN_DURATION_DEFAULT_MS = 500;
export const ANSWERS_SHOWN_DURATION_MAXIMUM_MS = 5000;
export const ANSWERS_SHOWN_DURATION_INFINTE = 0;
export const ANSWERS_SHOWN_DURATION_STEP = 500;
