import {
  LEVEL_EIGHT_FLAGS_AMOUNT,
  LEVEL_FIVE_FLAGS_AMOUNT,
  LEVEL_FOUR_FLAGS_AMOUNT,
  LEVEL_NINE_FLAGS_AMOUNT,
  LEVEL_ONE_FLAGS_AMOUNT,
  LEVEL_SEVEN_FLAGS_AMOUNT,
  LEVEL_SIX_FLAGS_AMOUNT,
  LEVEL_TEN_FLAGS_AMOUNT,
  LEVEL_THREE_FLAGS_AMOUNT,
  LEVEL_TWO_FLAGS_AMOUNT,
} from '@/constants/common';

export const mockCorruptProgressionData = {
  games: {
    standard: {
      levelOne: {
        id: 1,
        name: 'Level 1',
        isCompleted: false,
        isInProgress: false,
        isLocked: false,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelNine: {
        id: 9,
        name: 'Level 9',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelTen: {
        id: 10,
        name: 'Level 10',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
    },
    rapid: {
      levelTen: {
        id: 10,
        name: 'Level 10',
        isCompleted: false,

        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_TEN_FLAGS_AMOUNT,
      },
    },
    custom: {
      currentGame: {
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        scoreMultiplier: 0,
      },
      bestGame: {
        score: 0,
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        correct: 0,
        incorrect: 0,
        streak: 0,
      },
    },
    matchesPlayed: 0,
    totalCorrect: 1,
    totalIncorrect: 0,
    totalFail: true,
  },
  passport: [
    {
      countryCode: 'NO',
      countryName: 'Norway',
      continent: 'Europe',
      difficulty: 1,
      correctTotal: 1,
      incorrectTotal: 0,
      badKey: '',
    },
  ],
};

export const mockGoodProgressionData = {
  games: {
    standard: {
      levelOne: {
        id: 1,
        name: 'Level 1',
        isCompleted: false,
        isLocked: false,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelTwo: {
        id: 2,
        name: 'Level 2',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelThree: {
        id: 3,
        name: 'Level 3',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelFour: {
        id: 4,
        name: 'Level 4',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelFive: {
        id: 5,
        name: 'Level 5',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelSix: {
        id: 6,
        name: 'Level 6',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelSeven: {
        id: 7,
        name: 'Level 7',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelEight: {
        id: 8,
        name: 'Level 8',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelNine: {
        id: 9,
        name: 'Level 9',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelTen: {
        id: 10,
        name: 'Level 10',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
    },
    rapid: {
      levelOne: {
        id: 1,
        name: 'Level 1',
        isCompleted: false,
        isLocked: false,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_ONE_FLAGS_AMOUNT,
      },
      levelTwo: {
        id: 2,
        name: 'Level 2',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_TWO_FLAGS_AMOUNT,
      },
      levelThree: {
        id: 3,
        name: 'Level 3',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_THREE_FLAGS_AMOUNT,
      },
      levelFour: {
        id: 4,
        name: 'Level 4',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_FOUR_FLAGS_AMOUNT,
      },
      levelFive: {
        id: 5,
        name: 'Level 5',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_FIVE_FLAGS_AMOUNT,
      },
      levelSix: {
        id: 6,
        name: 'Level 6',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_SIX_FLAGS_AMOUNT,
      },
      levelSeven: {
        id: 7,
        name: 'Level 7',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_SEVEN_FLAGS_AMOUNT,
      },
      levelEight: {
        id: 8,
        name: 'Level 8',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_EIGHT_FLAGS_AMOUNT,
      },
      levelNine: {
        id: 9,
        name: 'Level 9',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_NINE_FLAGS_AMOUNT,
      },
      levelTen: {
        id: 10,
        name: 'Level 10',
        isCompleted: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: LEVEL_TEN_FLAGS_AMOUNT,
      },
    },
    custom: {
      currentGame: {
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        scoreMultiplier: 0,
      },
      bestGame: {
        score: 0,
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        correct: 0,
        incorrect: 0,
        streak: 0,
      },
    },
    matchesPlayed: 0,
    totalCorrect: 1,
    totalIncorrect: 0,
  },
  passport: [
    {
      countryCode: 'NO',
      countryName: 'Norway',
      continent: 'Europe',
      difficulty: 1,
      correctTotal: 1,
      incorrectTotal: 0,
    },
  ],
};

export const mockCorruptUserSettingsData = {
  isSetUp: false,
  isGoogleConnected: false,
  isPremiumUser: false,
  locale: 'en',
  isDarkTheme: false,
  energyAmount: 5,
  lastEnergyTimestamp: null,
  displayAnswerTimerMs: 500,
};

export const mockGoodUserSettingsData = {
  isSetUp: false,
  isGoogleConnected: false,
  userAgeForPersonalisation: null,
  isPremiumUser: false,
  locale: 'en',
  isDarkTheme: false,
  energyAmount: 5,
  lastEnergyTimestamp: null,
  noticeBoardLastVisitedDate: null,
  displayAnswerTimerMs: 500,
  userLevel: {
    totalExperience: 0,
    level: 1,
    currentLevelExperienceRequired: 200,
    experienceUntilNextLevelUp: 200,
    lastExperienceGainedDate: null,
    streak: 0,
  },
};
