import {
  ProgressionStructure,
  UserSettingStructure,
} from '@/types/secureStore';

export const defaultUserSettings: UserSettingStructure = {
  isSetup: false,
  locale: 'en',
};

export const defaultProgressionStructure: ProgressionStructure = {
  games: {
    standard: {
      levelOne: {
        id: 1,
        name: 'Level 1',
        isCompleted: false,
        isInProgress: false,
        isLocked: false,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelTwo: {
        id: 2,
        name: 'Level 2',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelThree: {
        id: 3,
        name: 'Level 3',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelFour: {
        id: 4,
        name: 'Level 4',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
      levelFive: {
        id: 5,
        name: 'Level 5',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 80,
        length: 10,
      },
    },
    rapid: {
      levelOne: {
        id: 1,
        name: 'Level 1',
        isCompleted: false,
        isInProgress: false,
        isLocked: false,
        userScore: 0,
        advancementRequirement: 15,
        length: 999,
      },
      levelTwo: {
        id: 2,
        name: 'Level 2',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: 999,
      },
      levelThree: {
        id: 3,
        name: 'Level 3',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: 999,
      },
      levelFour: {
        id: 4,
        name: 'Level 4',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: 999,
      },
      levelFive: {
        id: 5,
        name: 'Level 5',
        isCompleted: false,
        isInProgress: false,
        isLocked: true,
        userScore: 0,
        advancementRequirement: 15,
        length: 999,
      },
    },
    custom: {
      currentGame: {
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        scoreMultiplier: 0,
      },
      bestGame: {
        score: 0,
        regions: [],
        independentCountriesOnly: false,
        timeLimit: 0,
        gameLength: 0,
        correct: 0,
        incorrect: 0,
        streak: 0,
      },
    },
  },
};
